<?php

use Illuminate\Database\Seeder;

class SitiosTuristicosSeeder extends Seeder
{
	/**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
	    set_time_limit(0);

			$array_records = array (
				0 => array('islas_id' => '1', 'sitio' => 'Bartolomé', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				1 => array('islas_id' => '2', 'sitio' => 'Daphne Mayor', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				2 => array('islas_id' => '3', 'sitio' => 'Bahía Gardner', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				3 => array('islas_id' => '3', 'sitio' => 'Punta Suarez', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				4 => array('islas_id' => '4', 'sitio' => 'Punta Espinoza', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				5 => array('islas_id' => '5', 'sitio' => 'Asilo de la Paz', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				6 => array('islas_id' => '5', 'sitio' => 'Bahía Post Office', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				7 => array('islas_id' => '5', 'sitio' => 'Cerro Allieri', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				8 => array('islas_id' => '5', 'sitio' => 'La Lobería (F)', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				9 => array('islas_id' => '5', 'sitio' => 'La Misionera', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				10 => array('islas_id' => '5', 'sitio' => 'Mirador de la Baronesa', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				11 => array('islas_id' => '5', 'sitio' => 'Punta Cormorant', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				12 => array('islas_id' => '6', 'sitio' => 'Bahía Darwin', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				13 => array('islas_id' => '6', 'sitio' => 'El Barranco', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				14 => array('islas_id' => '7', 'sitio' => 'Bahía Cartago Grande', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				15 => array('islas_id' => '7', 'sitio' => 'Bahía Urbina', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				16 => array('islas_id' => '7', 'sitio' => 'Calera', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				17 => array('islas_id' => '7', 'sitio' => 'Caleta Tagus', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				18 => array('islas_id' => '7', 'sitio' => 'Centro de Crianza Arnaldo Tupiza', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				19 => array('islas_id' => '7', 'sitio' => 'Complejo de Humedales', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				20 => array('islas_id' => '7', 'sitio' => 'Concha de Perla', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				21 => array('islas_id' => '7', 'sitio' => 'Cueva de Sucre', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				22 => array('islas_id' => '7', 'sitio' => 'La Lobería (ISA)', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				23 => array('islas_id' => '7', 'sitio' => 'Los Túneles', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				24 => array('islas_id' => '7', 'sitio' => 'Minas de Azufre', 'actividades_id' => '2', 'created_at' => date('Y-m-d H:i:s')),
				25 => array('islas_id' => '7', 'sitio' => 'Mirador del Mango', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				26 => array('islas_id' => '7', 'sitio' => 'Muro de las Lágrimas', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				27 => array('islas_id' => '7', 'sitio' => 'Punta Albemarle', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				28 => array('islas_id' => '7', 'sitio' => 'Punta Moreno', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				29 => array('islas_id' => '7', 'sitio' => 'Tintoreras', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				30 => array('islas_id' => '7', 'sitio' => 'Volcán Alcedo', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				31 => array('islas_id' => '7', 'sitio' => 'Volcán Sierra Negra/V. Chico', 'actividades_id' => '2', 'created_at' => date('Y-m-d H:i:s')),
				32 => array('islas_id' => '7', 'sitio' => 'Lobería Grande II', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				33 => array('islas_id' => '7', 'sitio' => 'Punta Tortuga Negra', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				34 => array('islas_id' => '8', 'sitio' => 'Mosquera Norte', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				35 => array('islas_id' => '9', 'sitio' => 'Plaza Sur', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				36 => array('islas_id' => '10', 'sitio' => 'Rábida', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				37 => array('islas_id' => '11', 'sitio' => 'Bahía Rosa Blanca', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				38 => array('islas_id' => '11', 'sitio' => 'Bahía Sardina', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				39 => array('islas_id' => '11', 'sitio' => 'Centro de Crianza Jacinto Gordillo', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				40 => array('islas_id' => '11', 'sitio' => 'Centro de Interpretación', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				41 => array('islas_id' => '11', 'sitio' => 'Cerro Brujo', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				42 => array('islas_id' => '11', 'sitio' => 'Cerro Tijeretas', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				43 => array('islas_id' => '11', 'sitio' => 'El Junco', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				44 => array('islas_id' => '11', 'sitio' => 'Galapaguera Natural', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				45 => array('islas_id' => '11', 'sitio' => 'Isla Lobos', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				46 => array('islas_id' => '11', 'sitio' => 'Jardín de las Opuntias', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				47 => array('islas_id' => '11', 'sitio' => 'La Lobería (SC)', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				48 => array('islas_id' => '11', 'sitio' => 'Manglecito', 'actividades_id' => '2', 'created_at' => date('Y-m-d H:i:s')),
				49 => array('islas_id' => '11', 'sitio' => 'Playa Baquerizo', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				50 => array('islas_id' => '11', 'sitio' => 'Playa del Muerto', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				51 => array('islas_id' => '11', 'sitio' => 'Playa Ochoa', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				52 => array('islas_id' => '11', 'sitio' => 'Puerto Chino', 'actividades_id' => '2', 'created_at' => date('Y-m-d H:i:s')),
				53 => array('islas_id' => '11', 'sitio' => 'Puerto Grande', 'actividades_id' => '2', 'created_at' => date('Y-m-d H:i:s')),
				54 => array('islas_id' => '11', 'sitio' => 'Punta Carola', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				55 => array('islas_id' => '11', 'sitio' => 'Punta Pitt', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				56 => array('islas_id' => '11', 'sitio' => 'Punta Pucuna', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				57 => array('islas_id' => '11', 'sitio' => 'La Tortuga', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				58 => array('islas_id' => '12', 'sitio' => 'Bahía Ballena', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				59 => array('islas_id' => '12', 'sitio' => 'Bahía Borrero', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				60 => array('islas_id' => '12', 'sitio' => 'Centro de Crianza Fausto Llerena', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				61 => array('islas_id' => '12', 'sitio' => 'Cerro Dragón', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				62 => array('islas_id' => '12', 'sitio' => 'Garrapatero', 'actividades_id' => '2', 'created_at' => date('Y-m-d H:i:s')),
				63 => array('islas_id' => '12', 'sitio' => 'Isla Edén', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				64 => array('islas_id' => '12', 'sitio' => 'La Fe', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				65 => array('islas_id' => '12', 'sitio' => 'Laguna de las Ninfas', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				66 => array('islas_id' => '12', 'sitio' => 'La Ratonera', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				67 => array('islas_id' => '12', 'sitio' => 'Las Grietas', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				68 => array('islas_id' => '12', 'sitio' => 'Las Palmitas', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				69 => array('islas_id' => '12', 'sitio' => 'Los Gemelos', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				70 => array('islas_id' => '12', 'sitio' => 'Mirador de los Túneles', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				71 => array('islas_id' => '12', 'sitio' => 'Playa Estación Charles Darwin', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				72 => array('islas_id' => '12', 'sitio' => 'Playa de los Perros', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				73 => array('islas_id' => '12', 'sitio' => 'Playa de las Bachas', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				74 => array('islas_id' => '12', 'sitio' => 'Tortuga Bay', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				75 => array('islas_id' => '12', 'sitio' => 'Puntudo Cerro Crocker', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				76 => array('islas_id' => '12', 'sitio' => 'Reserva El Chato', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				77 => array('islas_id' => '12', 'sitio' => 'Playa Escondida', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				78 => array('islas_id' => '13', 'sitio' => 'Santa Fe/Fondeadero', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				79 => array('islas_id' => '14', 'sitio' => 'Bahía Sullivan', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				80 => array('islas_id' => '14', 'sitio' => 'Minas de Sal', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				81 => array('islas_id' => '14', 'sitio' => 'Playa Espumilla', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				82 => array('islas_id' => '14', 'sitio' => 'Puerto Egas', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				83 => array('islas_id' => '14', 'sitio' => 'Sombrero Chino', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				84 => array('islas_id' => '15', 'sitio' => 'Seymour Norte', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				85 => array('islas_id' => '16', 'sitio' => 'Baltra Noreste', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				86 => array('islas_id' => '16', 'sitio' => 'Baltra Noreste', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				87 => array('islas_id' => '16', 'sitio' => 'Baltra Noreste', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				88 => array('islas_id' => '1', 'sitio' => 'Roca Felipe', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				89 => array('islas_id' => '1', 'sitio' => 'Roca Felipe', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				90 => array('islas_id' => '1', 'sitio' => 'Bartolomé punta', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				91 => array('islas_id' => '1', 'sitio' => 'Bartolomé punta', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				92 => array('islas_id' => '17', 'sitio' => 'Daphne Menor', 'actividades_id' => '5', 'created_at' => date('Y-m-d H:i:s')),
				93 => array('islas_id' => '17', 'sitio' => 'Daphne Menor', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				94 => array('islas_id' => '18', 'sitio' => 'El Arco', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				95 => array('islas_id' => '18', 'sitio' => 'El Arco', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				96 => array('islas_id' => '18', 'sitio' => 'El Arenal', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				97 => array('islas_id' => '18', 'sitio' => 'El Arenal', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				98 => array('islas_id' => '3', 'sitio' => 'Bajo Gardner', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				99 => array('islas_id' => '3', 'sitio' => 'Islote Osborn', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				100 => array('islas_id' => '3', 'sitio' => 'Isla Gardner', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				101 => array('islas_id' => '3', 'sitio' => 'Isla Gardner', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				102 => array('islas_id' => '4', 'sitio' => 'Cabo Douglas', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				103 => array('islas_id' => '4', 'sitio' => 'Cabo Hammond', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				104 => array('islas_id' => '4', 'sitio' => 'Punta Mangle', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				105 => array('islas_id' => '4', 'sitio' => 'Punta Mangle', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				106 => array('islas_id' => '5', 'sitio' => 'Corona del Diablo', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				107 => array('islas_id' => '5', 'sitio' => 'Islote Caldwell', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				108 => array('islas_id' => '5', 'sitio' => 'Islote Champion', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				109 => array('islas_id' => '5', 'sitio' => 'Islote Champion', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				110 => array('islas_id' => '5', 'sitio' => 'Islote Champion', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				111 => array('islas_id' => '5', 'sitio' => 'IsloteEnderby', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				112 => array('islas_id' => '5', 'sitio' => 'Islote Gardner', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				113 => array('islas_id' => '5', 'sitio' => 'Islote Watson', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				114 => array('islas_id' => '5', 'sitio' => 'La Botella (F)', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				115 => array('islas_id' => '7', 'sitio' => 'Bahía Elizabeth', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				116 => array('islas_id' => '7', 'sitio' => 'Bahía Elizabeth', 'actividades_id' => '5', 'created_at' => date('Y-m-d H:i:s')),
				117 => array('islas_id' => '7', 'sitio' => 'Cabo Marshall', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				118 => array('islas_id' => '7', 'sitio' => 'Cabo Marshall', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				119 => array('islas_id' => '7', 'sitio' => 'Cabo Marshall', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				120 => array('islas_id' => '7', 'sitio' => 'Cabo Marshall', 'actividades_id' => '9', 'created_at' => date('Y-m-d H:i:s')),
				121 => array('islas_id' => '7', 'sitio' => 'Ciudad de las Mantas', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				122 => array('islas_id' => '7', 'sitio' => 'Ciudad de las Mantas', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				123 => array('islas_id' => '7', 'sitio' => 'Ciudad de las Mantas', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				124 => array('islas_id' => '7', 'sitio' => 'El Condenso', 'actividades_id' => '7', 'created_at' => date('Y-m-d H:i:s')),
				125 => array('islas_id' => '7', 'sitio' => 'El Estero', 'actividades_id' => '7', 'created_at' => date('Y-m-d H:i:s')),
				126 => array('islas_id' => '7', 'sitio' => 'El Finado', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				127 => array('islas_id' => '7', 'sitio' => 'El Finado', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				128 => array('islas_id' => '7', 'sitio' => 'El Finado', 'actividades_id' => '8', 'created_at' => date('Y-m-d H:i:s')),
				129 => array('islas_id' => '7', 'sitio' => 'Isla Cowley', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				130 => array('islas_id' => '7', 'sitio' => 'Isla Cowley', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				131 => array('islas_id' => '7', 'sitio' => 'Islote Tortuga', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				132 => array('islas_id' => '7', 'sitio' => 'Islote Tortuga', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				133 => array('islas_id' => '7', 'sitio' => 'Islote Tortuga', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				134 => array('islas_id' => '7', 'sitio' => 'Islote Tortuga', 'actividades_id' => '8', 'created_at' => date('Y-m-d H:i:s')),
				135 => array('islas_id' => '7', 'sitio' => 'Islote Tortuga Oeste', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				136 => array('islas_id' => '7', 'sitio' => 'La Angelita', 'actividades_id' => '7', 'created_at' => date('Y-m-d H:i:s')),
				137 => array('islas_id' => '7', 'sitio' => 'Playa Grande', 'actividades_id' => '7', 'created_at' => date('Y-m-d H:i:s')),
				138 => array('islas_id' => '7', 'sitio' => 'Puerto Coca', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				139 => array('islas_id' => '7', 'sitio' => 'Punta Vicente Roca', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				140 => array('islas_id' => '7', 'sitio' => 'Punta Vicente Roca', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				141 => array('islas_id' => '7', 'sitio' => 'Punta Vicente Roca', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				142 => array('islas_id' => '7', 'sitio' => 'Roca Blanca', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				143 => array('islas_id' => '7', 'sitio' => 'Roca Blanca', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				144 => array('islas_id' => '7', 'sitio' => 'Roca Blanca', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				145 => array('islas_id' => '7', 'sitio' => 'Roca Blanca', 'actividades_id' => '8', 'created_at' => date('Y-m-d H:i:s')),
				146 => array('islas_id' => '7', 'sitio' => 'Roca Redonda', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				147 => array('islas_id' => '7', 'sitio' => 'Roca Redonda', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				148 => array('islas_id' => '7', 'sitio' => 'Lobería Chica', 'actividades_id' => '10', 'created_at' => date('Y-m-d H:i:s')),
				149 => array('islas_id' => '7', 'sitio' => 'Arenero de El Faro', 'actividades_id' => '10', 'created_at' => date('Y-m-d H:i:s')),
				150 => array('islas_id' => '7', 'sitio' => 'Islote Cuatro Hermanos', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				151 => array('islas_id' => '7', 'sitio' => 'Islote Cuatro Hermanos', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				152 => array('islas_id' => '7', 'sitio' => 'Islote Cuatro Hermanos', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				153 => array('islas_id' => '19', 'sitio' => 'Playa Negra', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				154 => array('islas_id' => '19', 'sitio' => 'Playa Negra', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				155 => array('islas_id' => '19', 'sitio' => 'Punta Espejo', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				156 => array('islas_id' => '19', 'sitio' => 'Punta Mejía', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				157 => array('islas_id' => '19', 'sitio' => 'Punta Mejía', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				158 => array('islas_id' => '19', 'sitio' => 'Punta Mejía', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				159 => array('islas_id' => '19', 'sitio' => 'Punta Montalvo', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				160 => array('islas_id' => '19', 'sitio' => 'Punta Montalvo', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				161 => array('islas_id' => '19', 'sitio' => 'Punta Montalvo', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				162 => array('islas_id' => '20', 'sitio' => 'Cabo Chalmers', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				163 => array('islas_id' => '20', 'sitio' => 'Cabo Ibbetson', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				164 => array('islas_id' => '20', 'sitio' => 'Puerto Posada', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				165 => array('islas_id' => '20', 'sitio' => 'Punta Nerus', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				166 => array('islas_id' => '21', 'sitio' => 'Bahía Pingüino', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				167 => array('islas_id' => '21', 'sitio' => 'Bahía Pingüino', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				168 => array('islas_id' => '21', 'sitio' => 'Bahía Pingüino', 'actividades_id' => '8', 'created_at' => date('Y-m-d H:i:s')),
				169 => array('islas_id' => '21', 'sitio' => 'Islote Dumb', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				170 => array('islas_id' => '21', 'sitio' => 'Islote Dumb', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				171 => array('islas_id' => '21', 'sitio' => 'Roca Sin nombre', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				172 => array('islas_id' => '9', 'sitio' => 'Plaza Norte', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				173 => array('islas_id' => '9', 'sitio' => 'Plaza Norte', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				174 => array('islas_id' => '9', 'sitio' => 'Plaza Norte', 'actividades_id' => '5', 'created_at' => date('Y-m-d H:i:s')),
				175 => array('islas_id' => '9', 'sitio' => 'Plaza Norte', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				176 => array('islas_id' => '11', 'sitio' => 'Bajo de Cerro Brujo', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				177 => array('islas_id' => '11', 'sitio' => 'Caragua', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				178 => array('islas_id' => '11', 'sitio' => 'Caragua', 'actividades_id' => '10', 'created_at' => date('Y-m-d H:i:s')),
				179 => array('islas_id' => '11', 'sitio' => 'El Cañón', 'actividades_id' => '7', 'created_at' => date('Y-m-d H:i:s')),
				180 => array('islas_id' => '11', 'sitio' => 'Five Fingers', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				181 => array('islas_id' => '11', 'sitio' => 'Islote Punta Pitt', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				182 => array('islas_id' => '11', 'sitio' => 'Islote Punta Pitt', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				183 => array('islas_id' => '11', 'sitio' => 'Islote Punta Pitt', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				184 => array('islas_id' => '11', 'sitio' => 'La Predial', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				185 => array('islas_id' => '11', 'sitio' => 'La Predial', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				186 => array('islas_id' => '11', 'sitio' => 'La Predial', 'actividades_id' => '10', 'created_at' => date('Y-m-d H:i:s')),
				187 => array('islas_id' => '11', 'sitio' => 'León Dormido', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				188 => array('islas_id' => '11', 'sitio' => 'León Dormido', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				189 => array('islas_id' => '11', 'sitio' => 'León Dormido', 'actividades_id' => '7', 'created_at' => date('Y-m-d H:i:s')),
				190 => array('islas_id' => '11', 'sitio' => 'Lolo Surf', 'actividades_id' => '7', 'created_at' => date('Y-m-d H:i:s')),
				191 => array('islas_id' => '11', 'sitio' => 'Los Cráteres', 'actividades_id' => '7', 'created_at' => date('Y-m-d H:i:s')),
				192 => array('islas_id' => '11', 'sitio' => 'Pared Tijeretas', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				193 => array('islas_id' => '11', 'sitio' => 'Pared Tijeretas', 'actividades_id' => '10', 'created_at' => date('Y-m-d H:i:s')),
				194 => array('islas_id' => '11', 'sitio' => 'Roca Ballena', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				195 => array('islas_id' => '11', 'sitio' => 'Tongo Reef', 'actividades_id' => '7', 'created_at' => date('Y-m-d H:i:s')),
				196 => array('islas_id' => '11', 'sitio' => 'Outer Reef ', 'actividades_id' => '7', 'created_at' => date('Y-m-d H:i:s')),
				197 => array('islas_id' => '12', 'sitio' => 'Bajo Bazán', 'actividades_id' => '7', 'created_at' => date('Y-m-d H:i:s')),
				198 => array('islas_id' => '12', 'sitio' => 'Caamaño', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				199 => array('islas_id' => '12', 'sitio' => 'Caamaño', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				200 => array('islas_id' => '12', 'sitio' => 'Caamaño', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				201 => array('islas_id' => '12', 'sitio' => 'Caamaño', 'actividades_id' => '10', 'created_at' => date('Y-m-d H:i:s')),
				202 => array('islas_id' => '12', 'sitio' => 'Caleta Tortuga Negra', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				203 => array('islas_id' => '12', 'sitio' => 'Caleta Tortuga Negra', 'actividades_id' => '5', 'created_at' => date('Y-m-d H:i:s')),
				204 => array('islas_id' => '12', 'sitio' => 'Cerro Gallina', 'actividades_id' => '7', 'created_at' => date('Y-m-d H:i:s')),
				205 => array('islas_id' => '12', 'sitio' => 'El Bajo', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				206 => array('islas_id' => '12', 'sitio' => 'El Bajo', 'actividades_id' => '10', 'created_at' => date('Y-m-d H:i:s')),
				207 => array('islas_id' => '12', 'sitio' => 'El Barranco', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				208 => array('islas_id' => '12', 'sitio' => 'El Barranco', 'actividades_id' => '9', 'created_at' => date('Y-m-d H:i:s')),
				209 => array('islas_id' => '12', 'sitio' => 'El Barranco', 'actividades_id' => '10', 'created_at' => date('Y-m-d H:i:s')),
				210 => array('islas_id' => '12', 'sitio' => 'Guy Fawkes Sur', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				211 => array('islas_id' => '12', 'sitio' => 'Guy Fawkes Sur', 'actividades_id' => '5', 'created_at' => date('Y-m-d H:i:s')),
				212 => array('islas_id' => '12', 'sitio' => 'Guy Fawkes Sur', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				213 => array('islas_id' => '12', 'sitio' => 'Piedra Ahogada', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				214 => array('islas_id' => '12', 'sitio' => 'Piedra Ahogada', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				215 => array('islas_id' => '12', 'sitio' => 'Piedra Ahogada', 'actividades_id' => '8', 'created_at' => date('Y-m-d H:i:s')),
				216 => array('islas_id' => '12', 'sitio' => 'Punta Angermeyer', 'actividades_id' => '7', 'created_at' => date('Y-m-d H:i:s')),
				217 => array('islas_id' => '12', 'sitio' => 'Punta Carrión', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				218 => array('islas_id' => '12', 'sitio' => 'Punta Carrión', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				219 => array('islas_id' => '12', 'sitio' => 'Punta Carrión', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				220 => array('islas_id' => '12', 'sitio' => 'Punta Carrión Exterior', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				221 => array('islas_id' => '12', 'sitio' => 'Punta Estrada', 'actividades_id' => '5', 'created_at' => date('Y-m-d H:i:s')),
				222 => array('islas_id' => '12', 'sitio' => 'Punta Estrada', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				223 => array('islas_id' => '12', 'sitio' => 'Punta Estrada', 'actividades_id' => '7', 'created_at' => date('Y-m-d H:i:s')),
				224 => array('islas_id' => '12', 'sitio' => 'Punta Estrada', 'actividades_id' => '9', 'created_at' => date('Y-m-d H:i:s')),
				225 => array('islas_id' => '12', 'sitio' => 'Punta Estrada', 'actividades_id' => '10', 'created_at' => date('Y-m-d H:i:s')),
				226 => array('islas_id' => '12', 'sitio' => 'Punta Oeste Tortuga Bay', 'actividades_id' => '7', 'created_at' => date('Y-m-d H:i:s')),
				227 => array('islas_id' => '12', 'sitio' => 'Rocas Gordon', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				228 => array('islas_id' => '12', 'sitio' => 'Rocas Gordon', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				229 => array('islas_id' => '12', 'sitio' => 'Rocas Gordon', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				230 => array('islas_id' => '13', 'sitio' => 'La Botella (SF)', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				231 => array('islas_id' => '13', 'sitio' => 'La Botella (SF)', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				232 => array('islas_id' => '13', 'sitio' => 'La Botella (SF)', 'actividades_id' => '8', 'created_at' => date('Y-m-d H:i:s')),
				233 => array('islas_id' => '13', 'sitio' => 'Punta del Miedo', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				234 => array('islas_id' => '13', 'sitio' => 'La Encañada', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				235 => array('islas_id' => '13', 'sitio' => 'La Encañada', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				236 => array('islas_id' => '14', 'sitio' => 'Caleta Bucanero', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				237 => array('islas_id' => '14', 'sitio' => 'Caleta Bucanero', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				238 => array('islas_id' => '14', 'sitio' => 'Caleta Bucanero', 'actividades_id' => '5', 'created_at' => date('Y-m-d H:i:s')),
				239 => array('islas_id' => '14', 'sitio' => 'Islote Albany', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				240 => array('islas_id' => '14', 'sitio' => 'Islote Albany', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				241 => array('islas_id' => '14', 'sitio' => 'Islote Albany', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				242 => array('islas_id' => '14', 'sitio' => 'Roca Cousins', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				243 => array('islas_id' => '14', 'sitio' => 'Roca Cousins', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				244 => array('islas_id' => '14', 'sitio' => 'Roca Cousins', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				245 => array('islas_id' => '14', 'sitio' => 'Rocas Bainbridge', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				246 => array('islas_id' => '14', 'sitio' => 'Rocas Bainbridge', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				247 => array('islas_id' => '14', 'sitio' => 'Rocas Beagle', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				248 => array('islas_id' => '14', 'sitio' => 'Rocas Beagle', 'actividades_id' => '5', 'created_at' => date('Y-m-d H:i:s')),
				249 => array('islas_id' => '14', 'sitio' => 'Rocas Beagle', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				250 => array('islas_id' => '15', 'sitio' => 'Seymour canal', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				251 => array('islas_id' => '15', 'sitio' => 'Seymour canal', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				252 => array('islas_id' => '15', 'sitio' => 'Seymour Noreste', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				253 => array('islas_id' => '15', 'sitio' => 'Seymour Noreste', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				254 => array('islas_id' => '22', 'sitio' => 'Anchor Bay', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				255 => array('islas_id' => '22', 'sitio' => 'Anchor Bay', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				256 => array('islas_id' => '22', 'sitio' => 'El Derrumbe', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				257 => array('islas_id' => '22', 'sitio' => 'El Derrumbe', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				258 => array('islas_id' => '22', 'sitio' => 'El Derrumbe', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				259 => array('islas_id' => '22', 'sitio' => 'Islote la Ventana', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				260 => array('islas_id' => '22', 'sitio' => 'La Banana', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				261 => array('islas_id' => '22', 'sitio' => 'Punta Shark Bay', 'actividades_id' => '3', 'created_at' => date('Y-m-d H:i:s')),
				262 => array('islas_id' => '22', 'sitio' => 'Punta Shark Bay', 'actividades_id' => '4', 'created_at' => date('Y-m-d H:i:s')),
				263 => array('islas_id' => '22', 'sitio' => 'Punta Shark Bay', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				264 => array('islas_id' => '11', 'sitio' => 'Arrival', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				265 => array('islas_id' => '11', 'sitio' => 'Departure', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				266 => array('islas_id' => '11', 'sitio' => 'Arrival', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				267 => array('islas_id' => '16', 'sitio' => 'Departure', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				268 => array('islas_id' => '16', 'sitio' => 'Arrival', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				269 => array('islas_id' => '16', 'sitio' => 'Departure', 'actividades_id' => '1', 'created_at' => date('Y-m-d H:i:s')),
				270 => array('islas_id' => '16', 'sitio' => 'Arrival', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
				271 => array('islas_id' => '16', 'sitio' => 'Departure', 'actividades_id' => '6', 'created_at' => date('Y-m-d H:i:s')),
			);
		
		foreach (array_chunk($array_records, 1000) as $records) {
			\DB::table('sitios_turisticos')->insert($records);
		}
	}
}
